#!/bin/sh

# PROVIDE: madsonic
# REQUIRE: LOGIN
# KEYWORD: shutdown
#
# Add these lines to /etc/rc.conf.local or /etc/rc.conf
# to enable this service:
#
# madsonic_enable (bool):	Set to NO by default.
#				Set it to YES to enable bazarr.
# madsonic_dir: Directory where bazarr is installed
#             Default: /var/madsonic

. /etc/rc.subr

name="madsonic"
rcvar="${name}_enable"

#start_precmd="${name}_precmd"
stop_postcmd="${name}_postcmd"

load_rc_config $name
: ${madsonic_enable:="NO"}
: ${madsonic_dir:="/var/madsonic"}


pidfile="${madsonic_dir}/madsonic.pid"
command="./var/madsonic/madsonic.sh"
command_args="--pidfile ${pidfile}"

run_rc_command "$1"